# -*- coding: utf-8 -*-
"""Novel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tPgQ2_OwnD3QHAla2M8vHWcVpIjjUbqZ

### Manual Markovifying:
To build the database:
1. Select some [text to work](http://www.script-o-rama.com/movie_scripts/a1/bee-movie-script-transcript-seinfeld.html) with.
2. Create a spreadsheet
3. In column 1 of the sheet, list every unique word that occurs
4. In each row, starting with column 2, list every word that occurs after the word in column 1, including duplicates

To start building chains:
1. Select a random word from the first column
2. choose a random word from that word's row
3. Find that second word in the first column and continue

### OR

Use someone else's code
"""

# first, install a python package. This one is called "markovify"
# https://github.com/jsvine/markovify

!pip install markovify

!pip install markovify
!pip install weasyprint

import markovify
from weasyprint import HTML

novel = '<p>'
with open("DPCV.txt") as f:
  text = f.read()

text_model = markovify.Text(text)

for i in range(300):
    novel += str(text_model.make_sentence()) + " "

import random

# a general function for making paragraphs out of sentences
def make_paragraph():
  paragraph = 'Merry Christmas!  Don\'t let your Pokemon breathe the purple gas! '
  for i in range(random.randint(5,20)):
    paragraph += str(text_model.make_sentence())
  return paragraph

# THIS IS THE INTERESTING PART 
# initialize the HTML document
doc = dominate.document(title='Detective Pikachu\'s Christmas Vacation')

# add content to the HTML document
with doc:
  h1("Detective Pikachu's Christmas Vacation")
  for ch in range(10): # create 10 chapters
    h2("Chapter "+ str(int(ch + 1)))
    for para in range(random.randint(10,40)):
      p(make_paragraph())


# write the HTML document as a PDF
HTML(string=str(doc)).write_pdf("DPCV.pdf")

#print(novel)


html_template = f"""
<html>
  <head>
  <title>Detective Pikachu's Christmas Vacation</title>
  </head>
  <body>
  {novel}
  </body>
</html>
"""

HTML(string=html_template).write_pdf("Detective Pikachu's Christmas Vacation.pdf")